## [✔] COMPLETO

# Exercício:

In [28]:
import numpy as np
import pandas as pd

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

In [29]:
obj_1 = [1, 2, 3]
obj_2 = ["1", "2", "3"]
obj_3 = ["a", "b", "c"]

obj_composto = [
    obj_1,
    obj_2,
    obj_3
]

obj_composto

[[1, 2, 3], ['1', '2', '3'], ['a', 'b', 'c']]

R.: Sim, objetos compostos multidimensionais podem receber diversos objetos compostos unidimensionais.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [30]:
lista_genes = ["gloC", "ascA", "p54", "mtrABC", "piliIV"]

gloC = [len(lista_genes[0]),
        lista_genes[0][0:2],
        lista_genes[0].casefold().count("a"),
        "hu" in lista_genes[0].casefold()]

ascA = [len(lista_genes[1]),
        lista_genes[1][0:2],
        lista_genes[1].casefold().count("a"),
        "hu" in lista_genes[1].casefold()]

p54 = [len(lista_genes[2]),
       lista_genes[2][0:2],
       lista_genes[2].casefold().count("a"),
       "hu" in lista_genes[2].casefold()]

mtrABC = [len(lista_genes[3]),
         lista_genes[3][0:2],
         lista_genes[3].casefold().count("a"),
         "hu" in lista_genes[3].casefold()]

piliIV = [len(lista_genes[4]),
          lista_genes[4][0:2],
          lista_genes[4].casefold().count("a"),
          "hu" in lista_genes[4].casefold()]

matriz_genes = [gloC, ascA, p54, mtrABC, piliIV]

matriz_genes

#matriz.insert(postion, object)

[[4, 'gl', 0, False],
 [4, 'as', 2, False],
 [3, 'p5', 0, False],
 [6, 'mt', 1, False],
 [6, 'pi', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [31]:
matriz_np = np.array(matriz_genes)

matriz_np

array([['4', 'gl', '0', 'False'],
       ['4', 'as', '2', 'False'],
       ['3', 'p5', '0', 'False'],
       ['6', 'mt', '1', 'False'],
       ['6', 'pi', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [32]:
matriz_np[2]

array(['3', 'p5', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [33]:
matriz_np[:, -1]

array(['False', 'False', 'False', 'False', 'False'], dtype='<U21')

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [34]:
print(matriz_np[1, [1,2]])
print(matriz_np[3, [1,2]])

['as' '2']
['mt' '1']

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [35]:
dict_genes = {
    lista_genes[0]: gloC,
    lista_genes[1]: ascA,
    lista_genes[2]: p54,
    lista_genes[3]: mtrABC,
    lista_genes[4]: piliIV
}

df_genes = pd.DataFrame(dict_genes)

df_genes.to_csv("./data/genes_df.csv")

df_genes

    gloC   ascA    p54 mtrABC piliIV
0      4      4      3      6      6
1     gl     as     p5     mt     pi
2      0      2      0      1      0
3  False  False  False  False  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [36]:
print(df_genes.iloc[0])
print(df_genes.iloc[2])

gloC      4
ascA      4
p54       3
mtrABC    6
piliIV    6
Name: 0, dtype: object
gloC      0
ascA      2
p54       0
mtrABC    1
piliIV    0
Name: 2, dtype: object

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [37]:
print(df_genes.iloc[3, 0])
print(df_genes.iloc[3, 2])

False
False

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [38]:
data_df = pd.read_csv("./data/data.csv")


data_dict = {
    "Número de entradas": data_df.shape[0],
    "Classes das colunas": [type(column) for column in data_df.columns]
}

data_dict["Número de classe 'str'"] = [data_dict["Classes das colunas"].count(str)]

data_dict["Média"] = [data_df.iloc[:, 0].mean(),
                      data_df.iloc[:, 3].mean(),
                      data_df.iloc[:, 8].mean()]

data_dict["Desvio Padrão"] = [data_df.iloc[:, 0].std(),
                              data_df.iloc[:, 3].std(),
                              data_df.iloc[:, 8].std()]

data_dict["Terceiro Quartil"] = [data_df.iloc[:, 0].quantile(0.75),
                              data_df.iloc[:, 3].quantile(0.75),
                              data_df.iloc[:, 8].quantile(0.75)]

#data_df.info() # Informações gerais do DataFrame
#data_df.describe() # Descreve colunas quantitativas
#print(data_df.describe().iloc[2, [0, 3, 8]]) # Isolar valor descritivo
#data_df.select_dtypes(exclude="number").describe() # Descreve colunas qualitativas
data_dict

{'Número de entradas': 36634,
 'Classes das colunas': [str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str,
  str],
 "Número de classe 'str'": [18],
 'Média': [548661.9371894961, 731478.0068460993, 2571004.0973420865],
 'Desvio Padrão': [259912.9264939009, 17523003.588415086, 20367766.569178067],
 'Terceiro Quartil': [774252.0, 0.0, 1128871.1824999999]}

## Exercio Aula:

In [39]:
simbolo = [
    "IFNG",
    "Il10",
    "Tnf",
    "CSF2"
]

full_name = [
    "interferon gama",
    "interleukin 10",
    "tumor necrosis factor",
    "colony stimulating factor 2"
]

source = [
    "HGNC:HGNC:5438",
    "RGD:2886",
    "MGI:MGI:104798",
    "HGNC:HGNC:2434"
]

gene_type = [
    "protein coding",
    "protein coding",
    "protein coding",
    "protein coding"
]

organism = [
    "Homo sapiens",
    "Rattus novegicus",
    "Mus musculus",
    "Homo sapiens"
]

chromosome = [
    12,
    13,
    17,
    5
]

In [40]:
gene_matriz_lista = [
    simbolo,
    full_name,
    source,
    gene_type,
    organism,
    chromosome
]

In [41]:
gene_array = np.array(gene_matriz_lista)
gene_array

array([['IFNG', 'Il10', 'Tnf', 'CSF2'],
       ['interferon gama', 'interleukin 10', 'tumor necrosis factor',
        'colony stimulating factor 2'],
       ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
       ['protein coding', 'protein coding', 'protein coding',
        'protein coding'],
       ['Homo sapiens', 'Rattus novegicus', 'Mus musculus',
        'Homo sapiens'],
       ['12', '13', '17', '5']], dtype='<U27')

In [42]:
gene_array.shape

(6, 4)

In [43]:
gene_array[0, ]

array(['IFNG', 'Il10', 'Tnf', 'CSF2'], dtype='<U27')

In [44]:
gene_matriz_lista = {
    "simbolo": simbolo,
    "full_name": full_name,
    "source": source,
    "gene_type": gene_type,
    "organism": organism,
    "chromosome": chromosome
}

gene_matriz_lista

{'simbolo': ['IFNG', 'Il10', 'Tnf', 'CSF2'],
 'full_name': ['interferon gama',
  'interleukin 10',
  'tumor necrosis factor',
  'colony stimulating factor 2'],
 'source': ['HGNC:HGNC:5438', 'RGD:2886', 'MGI:MGI:104798', 'HGNC:HGNC:2434'],
 'gene_type': ['protein coding',
  'protein coding',
  'protein coding',
  'protein coding'],
 'organism': ['Homo sapiens',
  'Rattus novegicus',
  'Mus musculus',
  'Homo sapiens'],
 'chromosome': [12, 13, 17, 5]}

In [45]:
df_aula = pd.DataFrame(gene_matriz_lista)

df_aula

,simbolo,full_name,source,gene_type,organism,chromosome
0,IFNG,interferon gama,HGNC:HGNC:5438,protein coding,Homo sapiens,12
1,Il10,interleukin 10,RGD:2886,protein coding,Rattus novegicus,13
2,Tnf,tumor necrosis factor,MGI:MGI:104798,protein coding,Mus musculus,17
3,CSF2,colony stimulating factor 2,HGNC:HGNC:2434,protein coding,Homo sapiens,5