## [✔] COMPLETO

# Exercício:

In [13]:
import numpy as np
import pandas as pd

## 01 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:
<br>a) 2.0 + 3.0 / 5.0
<br>
<br>b) (a + 10.2) - 5.0 * 2.0
<br>
<br>c) a / b + 33.8
<br>
<br>d) a / (b + c)
<br>
<br>e) d * 2

In [15]:
ex_um_a = 2.0 + 3.0 / 5.0
ex_um_b = (ex_um_a + 10.2) - 5.0 * 2.0
ex_um_c = ex_um_a / ex_um_b + 33.8
ex_um_d = ex_um_a / (ex_um_b + ex_um_c)
ex_um_e = ex_um_d * 2

print(f"""R.: \n
    a) {ex_um_a} \n
    b) {ex_um_b} \n
    c) {ex_um_c} \n
    d) {ex_um_d} \n
    e) {ex_um_e} """)

R.:

    a) 2.6

    b) 2.799999999999999

    c) 34.72857142857143

    d) 0.0692805481537876

    e) 0.1385610963075752

## 02 – Obtenha os resultados e retorne o código em Python dos seguintes cálculos:
<br>
<br>a) [2.0, 3.0, 5.0] + [10, 20, 30]
<br>
<br>b) lista_a * 2
<br>
<br>c) lista_a + lista_b
<br>
<br>d) lista_a / (lista_b * lista_c)

In [16]:
lista_a = [2.0, 3.0, 5.0] + [10, 20, 30]
lista_b = lista_a * 2
lista_c = lista_a + lista_b
try:
    lista_d = lista_a / (lista_b * lista_c)
except TypeError as e:
    lista_d = f"Error: {e}"


print(f"""R.: \n
    a) {lista_a} \n
    b) {lista_b} \n
    c) {lista_c} \n
    e) Não se pode multiplicar/dividir uma lista por outra lista: \n {lista_d} \n 
    """)

R.:

    a) [2.0, 3.0, 5.0, 10, 20, 30]

    b) [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

    c) [2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30, 2.0, 3.0, 5.0, 10, 20, 30]

    e) Não se pode multiplicar/dividir uma lista por outra lista:
 Error: can't multiply sequence by non-int of type 'list'

## 03 – Usando os objetos simples obtidos no exercício 01, instancie uma  lista. Instancie também uma segunda lista contendo a raiz quadrada dos valores obtidos nos objetos simples. Instancie uma terceira lista, concatenando as duas primeiras. Recupere a última lista.

In [17]:
lista_tres_a = [ex_um_a, ex_um_b, ex_um_c, ex_um_d, ex_um_e]
lista_tres_b = [np.sqrt(x) for x in lista_tres_a]
lista_tres_c = lista_tres_a + lista_tres_b

lista_tres_a
lista_tres_b
lista_tres_c

[2.6,
 2.799999999999999,
 34.72857142857143,
 0.0692805481537876,
 0.1385610963075752,
 1.61245154965971,
 1.6733200530681507,
 5.893095233285427,
 0.263211983302029,
 0.3722379565648501]

## 04 – Duplique os valores contidos na lista final obtida no exercício anterior e converta para um array numpy. Remodele (reshape) o array, para que contenha 5 linhas e 4 colunas. Recupere o array.

In [18]:
lista_quatro_a = lista_tres_c * 2
array_quatro_a = np.array(lista_quatro_a)
array_quatro_b = array_quatro_a.reshape(5, 4)

array_quatro_b

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796]])

## 05 – Do array numpy obtenha uma lista contendo a média dos valores de cada uma das colunas.

In [20]:
lista_cinco_a = list(np.mean(array_quatro_b, axis=0))

lista_cinco_a

[7.8807329122498375, 2.1494130575327546, 7.8807329122498375, 2.149413057532755]

## 06 – O atributo shape pertence ao escopo dos objetos de classe numpy array. Ela retorna uma tupla onde o primeiro valor é o número de linhas e o segundo valor o de colunas contidas no array. Usando a informação do número total de valores presentes no numpy array do exercício 4 insira neste array a lista obtida no exercício 5. Recupere o array.
Obs.:  Atributos não usam () na chamada.

In [23]:
array_seis_a = np.concatenate((array_quatro_b,
                               np.array(lista_cinco_a)
                               .reshape(-1, array_quatro_b.shape[1])),
                               axis=0)

array_seis_a

array([[ 2.6       ,  2.8       , 34.72857143,  0.06928055],
       [ 0.1385611 ,  1.61245155,  1.67332005,  5.89309523],
       [ 0.26321198,  0.37223796,  2.6       ,  2.8       ],
       [34.72857143,  0.06928055,  0.1385611 ,  1.61245155],
       [ 1.67332005,  5.89309523,  0.26321198,  0.37223796],
       [ 7.88073291,  2.14941306,  7.88073291,  2.14941306]])

## 07 – Remodele (reshape) o array do exercício anterior, para que contenha 4 colunas. Converta este objeto da classe array para DataFrame. Arredonde todos os valores para até 3 casas decimais. Recupere a DataFrame.

In [24]:
array_sete_a = array_seis_a.reshape(-1, 4)

df_sete_a = pd.DataFrame(array_sete_a)

df_sete_a = df_sete_a.round(3)

df_sete_a

        0      1       2      3
0   2.600  2.800  34.729  0.069
1   0.139  1.612   1.673  5.893
2   0.263  0.372   2.600  2.800
3  34.729  0.069   0.139  1.612
4   1.673  5.893   0.263  0.372
5   7.881  2.149   7.881  2.149

## 08 – A última instancia desta DataFrame deve conter as médias dos valores contidos por coluna, o que foi determinado nos exercícios anteriores. Instancie um objeto contendo as médias dos valores em cada linha. Insira este objeto como uma nova coluna na DataFrame. Recupere a DataFrame.

In [25]:
df_medias_oito = df_sete_a.mean(axis=1)

df_oito_a = pd.concat((df_sete_a, df_medias_oito), axis=1).round(3)

df_oito_a

        0      1       2      3       0
0   2.600  2.800  34.729  0.069  10.050
1   0.139  1.612   1.673  5.893   2.329
2   0.263  0.372   2.600  2.800   1.509
3  34.729  0.069   0.139  1.612   9.137
4   1.673  5.893   0.263  0.372   2.050
5   7.881  2.149   7.881  2.149   5.015

## 09 – Usando o método dos objetos de classe DataFrame, describe(), compare os resultados contidos na última linha e última coluna da DataFrame.

Obs.: O método dos objetos de classe DataFrame, transpose(), inverte linhas por colunas.

In [26]:
df_nove_coluna = df_oito_a.iloc[:, -1].describe() # Última coluna
df_nove_linha = df_oito_a.iloc[-1, :].describe() # Última linha

display(df_nove_coluna, df_nove_linha)

count     6.000000
mean      5.015000
std       3.758722
min       1.509000
25%       2.119750
50%       3.672000
75%       8.106500
max      10.050000
Name: 0, dtype: float64

count    5.000
mean     5.015
std      2.866
min      2.149
25%      2.149
50%      5.015
75%      7.881
max      7.881
Name: 5, dtype: float64

## 10 – Edite o nome das colunas e dos index, para indicar onde estão as médias. Qual a média das médias?

In [27]:
df_oito_a.columns = [0, 1, 2, 3, "Médias"]
df_oito_a.index = [0, 1, 2, 3, 4, "Médias"]

display(df_oito_a)

media_das_medias_dez = (df_oito_a.iloc[-1, :].mean() + df_oito_a.iloc[:, -1].mean())/2

print(f"Média das médias (colunas e linhas) -> {media_das_medias_dez.round(3)}")

df_oito_a.to_csv("./data/df_atividade_07.csv")

             0      1       2      3  Médias
0        2.600  2.800  34.729  0.069  10.050
1        0.139  1.612   1.673  5.893   2.329
2        0.263  0.372   2.600  2.800   1.509
3       34.729  0.069   0.139  1.612   9.137
4        1.673  5.893   0.263  0.372   2.050
Médias   7.881  2.149   7.881  2.149   5.015

Média das médias (colunas e linhas) -> 5.015

## Exercícios Aula

In [14]:
num_1 = 4
num_2 = 2
print(num_1 + num_2)

6

In [15]:
tupla_1 = (1, 2, 3)
tupla_2 = (1, 2, 3)

print(tupla_1 == tupla_2)

True

In [22]:
array = np.array([1, 2, 75, 1, 20, 3, 1, 2, 3, 1, 20, 3])
array += 2
array

array([ 3,  4, 77,  3, 22,  5,  3,  4,  5,  3, 22,  5])

In [ ]:
np.insert(arr=np.array(['a', 'b']), obj=[-1], values=[1,2])

array(['a', '1', '2', 'b'], dtype='<U1')