## [✔] COMPLETO

# Exercício:

In [1]:
import pandas as pd
import numpy as np

## Instancie um objeto da classe lista contendo 5.000 valores inteiros iniciando em 0. 
Quantos são pares e quantos são impares?

## 01 – Descreva o racional da sua resposta:

R.: Consigo verificar se o número é par ou impar verificando se o resto da sua divisão por 2 é 0 ou não. Dessa forma, consigo usar uma estrutura de repetição juntamente com uma condicional para contar elementos pares.

## 02 – Desenhe o fluxograma da resposta:

<img src="./img/11-random_list.png" width="400" />

## 03 – Escreva o programa em Python:

In [2]:
lista_ex_um = list(np.random.randint(0, 10000, 5000))

lista_ex_um_pares = [num for num in lista_ex_um if num%2 == 0]
print(f"A lista tem {len(lista_ex_um)} valores.")
print(f"{len(lista_ex_um_pares)} são pares.")

A lista tem 5000 valores.
2457 são pares.

## 04 – Substitua a estrutura de repetição e responda novamente a pergunta anterior.

In [3]:
contador = 0
lista_ex_quatro_pares = []

while contador < len(lista_ex_um):
    if lista_ex_um[contador]%2 == 0:
        lista_ex_quatro_pares.append(lista_ex_um[contador])
    contador += 1
print(f"A lista tem {len(lista_ex_um)} valores.")
print(f"{len(lista_ex_quatro_pares)} são pares.")

A lista tem 5000 valores.
2457 são pares.

## Importe o .csv exportado na última aula e instancie um objeto da classe DataFrame.

Dos números de letras nos genes, quais são pares e quantos são impares?

In [4]:
genes_df = pd.read_csv("./data/genes_df.csv", index_col="Unnamed: 0")
genes_df.index = ["Número de caracteres", "Duas primeiras letras", "Contagem de 'a'", "Presença de 'hu'"]
genes_df = genes_df.T
genes_df["Número de caracteres"] = genes_df["Número de caracteres"].astype(int)

genes_df

,Número de caracteres,Duas primeiras letras,Contagem de 'a',Presença de 'hu'
gloC,4,gl,0,False
ascA,4,as,2,False
p54,3,p5,0,False
mtrABC,6,mt,1,False
piliIV,6,pi,0,False

## 05 – Descreva o racional da sua resposta:

R.: Usando uma estrutura de repetição em cima do número de caracteres, consigo aplicar mesma a lógica do resto da divisao por 2 == 0 em cada um dos elementos.

## 06 – Desenhe o fluxograma da resposta:

<img src="./img/11-genes_df.png" width="400" />

## 07 – Escreva o programa em Python:

In [5]:
genes_df["No. caracteres é par"] = [True if num%2 == 0 else False for num in genes_df["Número de caracteres"]]

genes_df

,Número de caracteres,Duas primeiras letras,Contagem de 'a',Presença de 'hu',No. caracteres é par
gloC,4,gl,0,False,True
ascA,4,as,2,False,True
p54,3,p5,0,False,False
mtrABC,6,mt,1,False,True
piliIV,6,pi,0,False,True

## 08 – Substitua a estrutura de repetição e responda novamente a pergunta anterior.

In [6]:
resultado = []
contador = 0

while contador < len(genes_df["Número de caracteres"]):
    num = genes_df["Número de caracteres"][contador]
    resultado.append(num % 2 == 0)
    contador += 1

genes_df["No. caracteres é par"] = resultado

genes_df

,Número de caracteres,Duas primeiras letras,Contagem de 'a',Presença de 'hu',No. caracteres é par
gloC,4,gl,0,False,True
ascA,4,as,2,False,True
p54,3,p5,0,False,False
mtrABC,6,mt,1,False,True
piliIV,6,pi,0,False,True

## 09 – Usando a coluna de presença de hu no nome do gene, itere os index deste objeto usando a função enumerate(). Estes index podem ser usados para imprimir cada um dos valores presentes na coluna dos dois primeiros caracteres dos nomes dos genes?

R.: Sim:

In [9]:
for index, value in enumerate(genes_df["Presença de \'hu\'"]):
    print(index, value)

0 False
1 False
2 False
3 False
4 False

In [10]:
for index, value in enumerate(genes_df["Presença de \'hu\'"]):
    print(genes_df["Duas primeiras letras"][index])

gl
as
p5
mt
pi

## 10 – Selecione qualquer uma das instâncias contidas na DataFrame. É possível recuperar as chaves e os valores com ao menos 3 estruturas de repetição diferentes?

R.: Sim:

In [30]:
for index, value in enumerate(genes_df.iloc[0]):
    print(index, value)

0 4
1 gl
2 0
3 False
4 True

In [29]:
contador = 0
while contador < len(genes_df.columns):
    print(genes_df.columns[contador], genes_df.iloc[0][genes_df.columns[contador]])
    contador += 1

Número de caracteres 4
Duas primeiras letras gl
Contagem de 'a' 0
Presença de 'hu' False
No. caracteres é par True

In [21]:
for key, value in genes_df.iloc[0].items():
    print(key, value)

Número de caracteres 4
Duas primeiras letras gl
Contagem de 'a' 0
Presença de 'hu' False
No. caracteres é par True

In [27]:

for index in range(len(genes_df)):
    colunas = [(key, value) for key, value in genes_df.iloc[index].items()]
    print(genes_df.index[index])
    print(colunas)

gloC
[('Número de caracteres', 4), ('Duas primeiras letras', 'gl'), ("Contagem de 'a'", '0'), ("Presença de 'hu'", 'False'), ('No. caracteres é par', True)]
ascA
[('Número de caracteres', 4), ('Duas primeiras letras', 'as'), ("Contagem de 'a'", '2'), ("Presença de 'hu'", 'False'), ('No. caracteres é par', True)]
p54
[('Número de caracteres', 3), ('Duas primeiras letras', 'p5'), ("Contagem de 'a'", '0'), ("Presença de 'hu'", 'False'), ('No. caracteres é par', False)]
mtrABC
[('Número de caracteres', 6), ('Duas primeiras letras', 'mt'), ("Contagem de 'a'", '1'), ("Presença de 'hu'", 'False'), ('No. caracteres é par', True)]
piliIV
[('Número de caracteres', 6), ('Duas primeiras letras', 'pi'), ("Contagem de 'a'", '0'), ("Presença de 'hu'", 'False'), ('No. caracteres é par', True)]